from flask import Flask,render_template

app = Flask(__name__)


@app.route('/')
def home():
    return render_template('home.html')

@app.route('/about')
def about():
    data=[{
              "title": "REMEDYREPACK INC.",
              "desc": "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum."
            }, {
              "title": "NCS HealthCare of KY, Inc dba Vangard Labs",
              "desc": "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc."
            }, {
              "title": "Meijer Distribution Inc",
              "desc": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam."
            }, {
              "title": "Cargo Cosmetics Corp.",
              "desc": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam."
            }, {
              "title": "West-ward Pharmaceutical Corp.",
              "desc": "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula."
            }, {
              "title": "McKesson Medical-Surgical",
              "desc": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor."
            }, {
              "title": "Alembic Pharmaceuticals Limited",
              "desc": "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat."
            }, {
              "title": "SCOT-TUSSIN Pharmacal Co., Inc.",
              "desc": "Integer non velit."
            }, {
              "title": "Select Brands distributors",
              "desc": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus."
            }, {
              "title": "Parfums Christian Dior",
              "desc": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl."
            }]
    return render_template('about.html', articles=data)

@app.route('/services')
def Our_Services():
    data=["John","Mary","Mike"]
    dataset = [
        {"id": 1, "first_name": "Lorie", "last_name": "Peace", "email": "lpeace0@paginegialle.it", "gender": "Female",
         "ip_address": "184.189.107.218"},
        {"id": 2, "first_name": "Nanice", "last_name": "Kollas", "email": "nkollas1@ameblo.jp", "gender": "Female",
         "ip_address": "176.161.146.56"},
        {"id": 3, "first_name": "Lutero", "last_name": "Whitford", "email": "lwhitford2@squarespace.com",
         "gender": "Male", "ip_address": "246.182.41.187"},
        {"id": 4, "first_name": "Othella", "last_name": "Tregian", "email": "otregian3@e-recht24.de",
         "gender": "Female", "ip_address": "240.154.20.67"},
        {"id": 5, "first_name": "Shela", "last_name": "Garthland", "email": "sgarthland4@symantec.com",
         "gender": "Female", "ip_address": "166.226.26.219"},
        {"id": 6, "first_name": "Cassandra", "last_name": "Figliovanni", "email": "cfigliovanni5@oakley.com",
         "gender": "Female", "ip_address": "135.24.106.70"},
        {"id": 7, "first_name": "Noah", "last_name": "Luckcock", "email": "nluckcock6@boston.com", "gender": "Male",
         "ip_address": "192.177.133.183"},
        {"id": 8, "first_name": "Augy", "last_name": "Vyel", "email": "avyel7@istockphoto.com", "gender": "Male",
         "ip_address": "101.10.186.97"},
        {"id": 9, "first_name": "Noland", "last_name": "Gwinnel", "email": "ngwinnel8@ezinearticles.com",
         "gender": "Male", "ip_address": "34.91.50.205"},
        {"id": 10, "first_name": "Birdie", "last_name": "Benning", "email": "bbenning9@ox.ac.uk", "gender": "Female",
         "ip_address": "88.228.192.111"},
        {"id": 11, "first_name": "Daphene", "last_name": "Gonnet", "email": "dgonneta@google.co.jp", "gender": "Female",
         "ip_address": "152.171.229.85"},
        {"id": 12, "first_name": "Celie", "last_name": "Caramuscia", "email": "ccaramusciab@slideshare.net",
         "gender": "Female", "ip_address": "115.197.69.241"},
        {"id": 13, "first_name": "Javier", "last_name": "Klimes", "email": "jklimesc@taobao.com", "gender": "Male",
         "ip_address": "26.104.253.86"},
        {"id": 14, "first_name": "Olwen", "last_name": "Cordet", "email": "ocordetd@printfriendly.com",
         "gender": "Female", "ip_address": "158.38.142.128"},
        {"id": 15, "first_name": "Wolfie", "last_name": "Snel", "email": "wsnele@acquirethisname.com", "gender": "Male",
         "ip_address": "95.184.27.132"},
        {"id": 16, "first_name": "Hew", "last_name": "Grishakov", "email": "hgrishakovf@tiny.cc", "gender": "Male",
         "ip_address": "134.187.156.89"},
        {"id": 17, "first_name": "Cchaddie", "last_name": "Giannasi", "email": "cgiannasig@ameblo.jp", "gender": "Male",
         "ip_address": "202.88.167.111"},
        {"id": 18, "first_name": "Sayer", "last_name": "Kop", "email": "skoph@altervista.org", "gender": "Male",
         "ip_address": "244.98.146.16"},
        {"id": 19, "first_name": "Fionna", "last_name": "Wicklin", "email": "fwicklini@dagondesign.com",
         "gender": "Female", "ip_address": "9.63.161.10"},
        {"id": 20, "first_name": "Tobye", "last_name": "Upshall", "email": "tupshallj@disqus.com", "gender": "Female",
         "ip_address": "205.157.5.24"},
        {"id": 21, "first_name": "Heidie", "last_name": "Cordobes", "email": "hcordobesk@loc.gov", "gender": "Female",
         "ip_address": "234.227.138.57"},
        {"id": 22, "first_name": "Shirline", "last_name": "Jillings", "email": "sjillingsl@nature.com",
         "gender": "Female", "ip_address": "228.68.128.91"},
        {"id": 23, "first_name": "Kat", "last_name": "Carl", "email": "kcarlm@arizona.edu", "gender": "Female",
         "ip_address": "26.123.89.84"},
        {"id": 24, "first_name": "Ferdie", "last_name": "Benterman", "email": "fbentermann@newyorker.com",
         "gender": "Male", "ip_address": "97.75.111.105"},
        {"id": 25, "first_name": "Renie", "last_name": "Cowlam", "email": "rcowlamo@t-online.de", "gender": "Female",
         "ip_address": "226.150.66.175"},
        {"id": 26, "first_name": "Mady", "last_name": "Wetherburn", "email": "mwetherburnp@ycombinator.com",
         "gender": "Female", "ip_address": "145.193.48.91"},
        {"id": 27, "first_name": "Norton", "last_name": "Pearmain", "email": "npearmainq@wsj.com", "gender": "Male",
         "ip_address": "5.106.84.33"},
        {"id": 28, "first_name": "Paddie", "last_name": "Stone", "email": "pstoner@nhs.uk", "gender": "Male",
         "ip_address": "178.52.201.48"},
        {"id": 29, "first_name": "Stacia", "last_name": "Batterbee", "email": "sbatterbees@sakura.ne.jp",
         "gender": "Female", "ip_address": "179.131.92.195"},
        {"id": 30, "first_name": "Ettore", "last_name": "Flippelli", "email": "eflippellit@marriott.com",
         "gender": "Male", "ip_address": "134.205.192.80"},
        {"id": 31, "first_name": "Kristian", "last_name": "Redfield", "email": "kredfieldu@dedecms.com",
         "gender": "Male", "ip_address": "2.8.254.204"},
        {"id": 32, "first_name": "Gwendolen", "last_name": "Lenin", "email": "gleninv@ezinearticles.com",
         "gender": "Female", "ip_address": "54.16.218.46"},
        {"id": 33, "first_name": "Petronia", "last_name": "Hardiker", "email": "phardikerw@booking.com",
         "gender": "Female", "ip_address": "74.253.113.46"},
        {"id": 34, "first_name": "Husein", "last_name": "Letherbury", "email": "hletherburyx@youku.com",
         "gender": "Male", "ip_address": "138.80.210.226"},
        {"id": 35, "first_name": "Franchot", "last_name": "Whittek", "email": "fwhitteky@miitbeian.gov.cn",
         "gender": "Male", "ip_address": "50.159.226.21"},
        {"id": 36, "first_name": "Paulie", "last_name": "Turk", "email": "pturkz@123-reg.co.uk", "gender": "Female",
         "ip_address": "104.214.136.18"},
        {"id": 37, "first_name": "Ulrich", "last_name": "Sellers", "email": "usellers10@redcross.org", "gender": "Male",
         "ip_address": "133.113.62.59"},
        {"id": 38, "first_name": "Tomaso", "last_name": "Patmore", "email": "tpatmore11@webnode.com", "gender": "Male",
         "ip_address": "92.92.75.241"},
        {"id": 39, "first_name": "Imogen", "last_name": "Tookill", "email": "itookill12@barnesandnoble.com",
         "gender": "Female", "ip_address": "49.213.168.118"},
        {"id": 40, "first_name": "Georgena", "last_name": "Pachmann", "email": "gpachmann13@yellowbook.com",
         "gender": "Female", "ip_address": "120.230.192.44"},
        {"id": 41, "first_name": "Elianore", "last_name": "Kloster", "email": "ekloster14@techcrunch.com",
         "gender": "Female", "ip_address": "233.99.95.6"},
        {"id": 42, "first_name": "Roland", "last_name": "Weeke", "email": "rweeke15@fotki.com", "gender": "Male",
         "ip_address": "72.65.127.185"},
        {"id": 43, "first_name": "Mickie", "last_name": "Ambrogelli", "email": "mambrogelli16@google.it",
         "gender": "Female", "ip_address": "18.180.111.150"},
        {"id": 44, "first_name": "Gino", "last_name": "Lebreton", "email": "glebreton17@zdnet.com", "gender": "Male",
         "ip_address": "203.185.59.113"},
        {"id": 45, "first_name": "Mahmoud", "last_name": "Oret", "email": "moret18@a8.net", "gender": "Male",
         "ip_address": "97.90.80.178"},
        {"id": 46, "first_name": "Eldin", "last_name": "Fitzsimmons", "email": "efitzsimmons19@google.co.jp",
         "gender": "Male", "ip_address": "48.5.161.165"},
        {"id": 47, "first_name": "Eadmund", "last_name": "Wevell", "email": "ewevell1a@washingtonpost.com",
         "gender": "Male", "ip_address": "194.137.79.83"},
        {"id": 48, "first_name": "Pearle", "last_name": "Alaway", "email": "palaway1b@cdc.gov", "gender": "Female",
         "ip_address": "251.235.207.240"},
        {"id": 49, "first_name": "Arnie", "last_name": "Dank", "email": "adank1c@t-online.de", "gender": "Male",
         "ip_address": "87.94.181.55"},
        {"id": 50, "first_name": "Mitchael", "last_name": "Mowen", "email": "mmowen1d@unc.edu", "gender": "Male",
         "ip_address": "168.198.254.79"},
        {"id": 51, "first_name": "Bartholomeo", "last_name": "Ennever", "email": "bennever1e@altervista.org",
         "gender": "Male", "ip_address": "184.125.158.198"},
        {"id": 52, "first_name": "Ermanno", "last_name": "McGarvie", "email": "emcgarvie1f@disqus.com",
         "gender": "Male", "ip_address": "57.214.68.165"},
        {"id": 53, "first_name": "Thedrick", "last_name": "Pettus", "email": "tpettus1g@meetup.com", "gender": "Male",
         "ip_address": "156.212.31.121"},
        {"id": 54, "first_name": "Ware", "last_name": "Cahalin", "email": "wcahalin1h@si.edu", "gender": "Male",
         "ip_address": "212.133.156.5"},
        {"id": 55, "first_name": "Vidovik", "last_name": "Wytchard", "email": "vwytchard1i@cargocollective.com",
         "gender": "Male", "ip_address": "244.241.141.214"},
        {"id": 56, "first_name": "Jock", "last_name": "Laddle", "email": "jladdle1j@lycos.com", "gender": "Male",
         "ip_address": "208.251.231.208"},
        {"id": 57, "first_name": "Darius", "last_name": "Lackmann", "email": "dlackmann1k@webmd.com", "gender": "Male",
         "ip_address": "147.12.230.238"},
        {"id": 58, "first_name": "Anderson", "last_name": "French", "email": "afrench1l@addtoany.com", "gender": "Male",
         "ip_address": "168.14.142.82"},
        {"id": 59, "first_name": "Ragnar", "last_name": "Dockray", "email": "rdockray1m@lycos.com", "gender": "Male",
         "ip_address": "198.43.123.88"},
        {"id": 60, "first_name": "Tabby", "last_name": "Foat", "email": "tfoat1n@goo.gl", "gender": "Female",
         "ip_address": "113.4.100.122"},
        {"id": 61, "first_name": "Gregoor", "last_name": "Terese", "email": "gterese1o@hexun.com", "gender": "Male",
         "ip_address": "136.141.140.220"},
        {"id": 62, "first_name": "Kimble", "last_name": "Emslie", "email": "kemslie1p@about.com", "gender": "Male",
         "ip_address": "142.174.234.24"},
        {"id": 63, "first_name": "Demetri", "last_name": "Kivell", "email": "dkivell1q@ihg.com", "gender": "Male",
         "ip_address": "59.250.36.147"},
        {"id": 64, "first_name": "Nicola", "last_name": "Reynoldson", "email": "nreynoldson1r@mozilla.com",
         "gender": "Male", "ip_address": "79.196.168.108"},
        {"id": 65, "first_name": "Kaine", "last_name": "Darcey", "email": "kdarcey1s@admin.ch", "gender": "Male",
         "ip_address": "73.170.173.40"},
        {"id": 66, "first_name": "Antonin", "last_name": "Luxon", "email": "aluxon1t@phpbb.com", "gender": "Male",
         "ip_address": "213.255.129.64"},
        {"id": 67, "first_name": "Sibyl", "last_name": "Jeanequin", "email": "sjeanequin1u@army.mil",
         "gender": "Female", "ip_address": "25.241.215.16"},
        {"id": 68, "first_name": "Daile", "last_name": "Letts", "email": "dletts1v@yandex.ru", "gender": "Female",
         "ip_address": "151.121.100.65"},
        {"id": 69, "first_name": "Belita", "last_name": "Gecks", "email": "bgecks1w@domainmarket.com",
         "gender": "Female", "ip_address": "69.14.50.27"},
        {"id": 70, "first_name": "Dierdre", "last_name": "Emmines", "email": "demmines1x@imgur.com", "gender": "Female",
         "ip_address": "255.44.110.182"},
        {"id": 71, "first_name": "Jayme", "last_name": "Aylesbury", "email": "jaylesbury1y@ted.com", "gender": "Female",
         "ip_address": "154.84.140.157"},
        {"id": 72, "first_name": "Brandyn", "last_name": "Milington", "email": "bmilington1z@slideshare.net",
         "gender": "Male", "ip_address": "88.106.241.211"},
        {"id": 73, "first_name": "Quintina", "last_name": "Podmore", "email": "qpodmore20@photobucket.com",
         "gender": "Female", "ip_address": "25.110.232.178"},
        {"id": 74, "first_name": "Giulietta", "last_name": "Hehl", "email": "ghehl21@mapquest.com", "gender": "Female",
         "ip_address": "37.202.155.207"},
        {"id": 75, "first_name": "Engelbert", "last_name": "Lovett", "email": "elovett22@addthis.com", "gender": "Male",
         "ip_address": "185.164.69.108"},
        {"id": 76, "first_name": "Bethanne", "last_name": "Peppard", "email": "bpeppard23@digg.com", "gender": "Female",
         "ip_address": "212.21.251.207"},
        {"id": 77, "first_name": "Keenan", "last_name": "Duffield", "email": "kduffield24@pinterest.com",
         "gender": "Male", "ip_address": "164.215.38.9"},
        {"id": 78, "first_name": "Lorettalorna", "last_name": "Cordes", "email": "lcordes25@google.co.uk",
         "gender": "Female", "ip_address": "27.61.7.209"},
        {"id": 79, "first_name": "Katharina", "last_name": "Rizzetti", "email": "krizzetti26@si.edu",
         "gender": "Female", "ip_address": "105.53.197.31"},
        {"id": 80, "first_name": "Franny", "last_name": "Seden", "email": "fseden27@goodreads.com", "gender": "Male",
         "ip_address": "202.28.75.130"},
        {"id": 81, "first_name": "Raphael", "last_name": "Renals", "email": "rrenals28@slashdot.org", "gender": "Male",
         "ip_address": "211.48.194.238"},
        {"id": 82, "first_name": "Jennette", "last_name": "Finlan", "email": "jfinlan29@nature.com", "gender": "Female",
         "ip_address": "71.244.109.18"},
        {"id": 83, "first_name": "Vincent", "last_name": "Rebillard", "email": "vrebillard2a@github.io",
         "gender": "Male", "ip_address": "71.45.164.140"},
        {"id": 84, "first_name": "Blancha", "last_name": "McDonogh", "email": "bmcdonogh2b@tamu.edu",
         "gender": "Female", "ip_address": "2.114.142.216"},
        {"id": 85, "first_name": "Tiphany", "last_name": "Groucock", "email": "tgroucock2c@linkedin.com",
         "gender": "Female", "ip_address": "20.209.38.75"},
        {"id": 86, "first_name": "Donni", "last_name": "Stockings", "email": "dstockings2d@last.fm", "gender": "Female",
         "ip_address": "134.226.119.193"},
        {"id": 87, "first_name": "Marena", "last_name": "Eveling", "email": "meveling2e@nsw.gov.au", "gender": "Female",
         "ip_address": "128.181.141.122"},
        {"id": 88, "first_name": "Dita", "last_name": "Anglim", "email": "danglim2f@people.com.cn", "gender": "Female",
         "ip_address": "119.97.59.26"},
        {"id": 89, "first_name": "Jerrome", "last_name": "Angeau", "email": "jangeau2g@indiatimes.com",
         "gender": "Male", "ip_address": "216.125.244.97"},
        {"id": 90, "first_name": "Jorgan", "last_name": "Felton", "email": "jfelton2h@privacy.gov.au", "gender": "Male",
         "ip_address": "78.187.103.56"},
        {"id": 91, "first_name": "Ceil", "last_name": "Millier", "email": "cmillier2i@baidu.com", "gender": "Female",
         "ip_address": "61.20.228.110"},
        {"id": 92, "first_name": "Emilia", "last_name": "Muddle", "email": "emuddle2j@clickbank.net",
         "gender": "Female", "ip_address": "98.198.31.116"},
        {"id": 93, "first_name": "Kelbee", "last_name": "Ducket", "email": "kducket2k@army.mil", "gender": "Male",
         "ip_address": "172.22.82.120"},
        {"id": 94, "first_name": "Etan", "last_name": "Apfelmann", "email": "eapfelmann2l@cargocollective.com",
         "gender": "Male", "ip_address": "222.1.138.231"},
        {"id": 95, "first_name": "Gerald", "last_name": "Jirasek", "email": "gjirasek2m@army.mil", "gender": "Male",
         "ip_address": "185.204.141.35"},
        {"id": 96, "first_name": "Huntlee", "last_name": "Brecher", "email": "hbrecher2n@gmpg.org", "gender": "Male",
         "ip_address": "74.74.75.17"},
        {"id": 97, "first_name": "Faina", "last_name": "Spurling", "email": "fspurling2o@quantcast.com",
         "gender": "Female", "ip_address": "9.122.77.250"},
        {"id": 98, "first_name": "Donella", "last_name": "McCreery", "email": "dmccreery2p@163.com", "gender": "Female",
         "ip_address": "170.46.90.176"},
        {"id": 99, "first_name": "Edie", "last_name": "Shutle", "email": "eshutle2q@tinypic.com", "gender": "Female",
         "ip_address": "124.113.204.20"},
        {"id": 100, "first_name": "Melli", "last_name": "Somerfield", "email": "msomerfield2r@so-net.ne.jp",
         "gender": "Female", "ip_address": "145.104.159.228"}]
    return render_template('services.html', names=data, customers=dataset)


@app.errorhandler(404)
def error(e):
    return  "page not found"
if __name__ == '__main__':
    app.run()
